SIM           = icarus
TOPLEVEL_LANG = verilog
COMPILE_ARGS  = -g2012

VERILOG_SOURCES = ../../rtl/src/accumulator_bank.sv
TOPLEVEL        = accumulator_bank
MODULE          = test_accumulator_bank

include $(shell cocotb-config --makefiles)/Makefile.sim
