SIM           = icarus
TOPLEVEL_LANG = verilog
COMPILE_ARGS  = -g2012

VERILOG_SOURCES = ../../rtl/src/pe.sv ../../rtl/src/systolic_array.sv
TOPLEVEL        = systolic_array
MODULE          = test_systolic_array

include $(shell cocotb-config --makefiles)/Makefile.sim
