MODELSIM_ENV ?= /vol/eecs392/env/modelsim.env
RTL          = ../../rtl/src/systolic_data_setup.sv
TOP          = systolic_data_setup
WORK         = work

ifeq ($(MODELSIM_LOADED),1)

.PHONY: compile wave clean

compile:
	vlib $(WORK)
	vlog -sv $(RTL)

wave: compile
	vsim -do "add wave -r /*; run -all; wave zoom full" $(TOP)

clean:
	rm -rf $(WORK) vsim.wlf transcript

else
%:
	@bash -c ". $(MODELSIM_ENV) && MODELSIM_LOADED=1 $(MAKE) -f Makefile.modelsim $@"
endif
