SIM           = icarus
TOPLEVEL_LANG = verilog
COMPILE_ARGS  = -g2012

VERILOG_SOURCES = ../../rtl/src/systolic_data_setup.sv
TOPLEVEL        = systolic_data_setup
MODULE          = test_systolic_data_setup

include $(shell cocotb-config --makefiles)/Makefile.sim
