SIM           = icarus
TOPLEVEL_LANG = verilog
COMPILE_ARGS  = -g2012

VERILOG_SOURCES = ../../rtl/src/pe.sv
TOPLEVEL        = pe
MODULE          = test_pe

include $(shell cocotb-config --makefiles)/Makefile.sim
